### ISSUE TITLE
Update Scholarly Articles

### ISSUE THREAD

**Issue by AlexanderKidd** [AlexanderKidd/SWEN-444-Pipeline#2]
-Text and icons as per our class activity revisions
-Make a dummy scholarly article page with some basic text (make it look official though).

**Comment by hqp6684** [comment]
- [x] Make a dummy scholarly article page with some basic text (make it look official though).  https://github.com/AlexanderKidd/SWEN-444-Pipeline/commit/6f127657a6e75f15a47d62a3a2c15f2108f6eb51

**Comment by AlexanderKidd** [comment]
Thanks for picking this up, looks good.
