### ISSUE TITLE
Create Login Page/Auth Cookies

### ISSUE THREAD

**Issue by AlexanderKidd** [AlexanderKidd/SWEN-444-Pipeline#5]
-Text and icons as per our class activity revisions (or what is consistent with pages)
-Name, Email, dummy password of sorts should really be the only things necessary.
-Maybe a picture for the top right corner of navbar.

**Comment by sxHelloWorld** [comment]
Index.html is updated and login.html and register.html are created. They work as setting a cookie with one value for username

**Comment by AlexanderKidd** [comment]
Great!  Next step might be to use it per page.  But that's fine for now, logging in may be a testing task.
