### ISSUE TITLE
Update Homepage

### ISSUE THREAD

**Issue by AlexanderKidd** [AlexanderKidd/SWEN-444-Pipeline#8]
- [x] Text and icons as per our class activity revisions
- [x] Make sure it looks cohesive, proportions are correct.
- [x] Use local storage to create a support globe marker based on form.
(Note: Hardcoded Lat/Long to Rochester, NY.  Conversions would be a little beyond the scope of this interaction prototype.)
- [x] Related news sidebar could be toggled with an arrow.

**Comment by hqp6684** [comment]
Related news sidebar could be toggled with ~~an arrow~~ option from main menu
https://github.com/AlexanderKidd/SWEN-444-Pipeline/commit/605371a949cbf6fe264f6827b8a9c50cf63f0ab7
